apiVersion: v1
kind: Service
metadata:
  name: fm-ad-app-01
  namespace: fmad-demo
  labels:
    app.kubernetes.io/name: fm-ad-app-01
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: fm-ad-app-01
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000